version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306

  backend:
    image: jioome/culture-stamp:latest
#    build: .
    container_name: culture-stamp-d
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
